### ISSUE TITLE
Identifying subscription intent

### ISSUE THREAD

**Issue by SeanFeldman** [Azure-Samples/event-grid-relay-listener#4]
Currently, the sample is looking at individual event message for an event of type `Microsoft.EventGrid.SubscriptionValidationEvent`. Should it rather look at `Aeg-Event-Type` header with `SubscriptionValidation` value as documented [here](https://docs.microsoft.com/en-us/azure/event-grid/security-authentication)?

**Comment by banisadr** [comment]
Both options work - we have parallel ways of identifying the validation event - header if you want to not deserialize the event, and event type if you want to put your validation response into the flow control for your event handling of various event types (assumption is you deserialize the event at that point either way).

I'll put out a second sample for the 'router' type scenario in which you'd like to hand off the event to a secondary system if its not a validation event (scenario in which you do not wish to deserialize here).
